
---
title: "Profiling Spatial modelling Analysis"
author: "Job Spijker"
output: 
  html_document:
    highlight: tango
    toc: true
    toc_depth: 3
    number_sections: true
    fig_caption: yes
urlcolor: blue    
---

```{r}

remotes::install_github("gearslaboratory/gdalUtils")
remotes::install_github("jspijker/datafile")

# init
library(rgdal)
library(gdalUtils)
library(sf)
library(microbenchmark)
library(raster)
library(datafile)
datafileInit()
library(ranger)
library(Boruta)
```

# Introduction

Some tests to see what happens with parallel processing of data


Create to rasters with different geometry, and then resample to a
single geometry. 

```{r}

# Create raster, use Dutch RD extent
createRast <- function(xmin=0,xmax=280000,
                        ymin=300000,ymax=625000,
                        resolution=25) {

    xcells=(xmax-xmin)/resolution
    ycells=(ymax-ymin)/resolution

    x <- raster::raster(xmn=xmin,
                xmx=xmax,
                ymn=ymin,
                ymx=ymax,
                nrows=ycells,
                ncols=xcells,
                crs=CRS("+init=epsg:28992")
                )


    #x[] <- 1:ncell(x)
    x[] <- round(runif(n = ncell(x), min = 0, max = 1000))
    return(x)
}

size <- 100000
t1 <- system.time(r1 <- createRast(xmin = 0, xmax = size, 
                                   ymin = 0, ymax = size))
r2 <- createRast(xmin = 0, xmax = size, ymin = 0, ymax = size,
                 resolution = 430)

resample_rast <- function(){

    beginCluster(n = 2)
    t2 <- system.time(
                      new.rast <- resample(r1,r2,method="ngb")
    )
    endCluster()

}

b <- microbenchmark(resample_rast(), times = 10)
b


```



